drivers/i2c/i2c-core.ko
drivers/hwmon/hwmon.ko

net/llc/llc.ko
net/802/stp.ko
net/bridge/bridge.ko
drivers/net/mdio.ko
drivers/net/phy/mdio-bus.ko
drivers/net/phy/libphy.ko
drivers/net/phy/mdio_devres.ko
drivers/net/mii.ko

drivers/pcmcia/pcmcia_core.ko
drivers/pcmcia/pcmcia_rsrc.ko
drivers/pcmcia/yenta_socket.ko
drivers/pcmcia/pcmcia.ko
drivers/mmc/core/mmc_core.ko

drivers/ssb/ssb.ko

drivers/net/ethernet/broadcom/b44.ko
drivers/net/ethernet/broadcom/tg3.ko
drivers/net/ethernet/intel/e1000/e1000.ko
drivers/net/ethernet/intel/e1000e/e1000e.ko
drivers/net/ethernet/realtek/r8169.ko
drivers/net/ethernet/realtek/8139too.ko

net/rfkill/rfkill.ko
lib/crypto/libarc4.ko
net/wireless/cfg80211.ko
net/mac80211/mac80211.ko

drivers/net/wireless/intel/ipw2x00/libipw.ko
drivers/net/wireless/intel/ipw2x00/ipw2200.ko

drivers/block/loop.ko
fs/squashfs/squashfs.ko

drivers/usb/common/usb-common.ko
drivers/usb/core/usbcore.ko
drivers/usb/host/xhci-hcd.ko
drivers/usb/host/xhci-pci.ko
drivers/usb/host/ehci-hcd.ko
drivers/usb/host/ehci-pci.ko

drivers/hid/hid.ko
drivers/hid/hid-generic.ko
drivers/hid/usbhid/usbhid.ko
drivers/input/evdev.ko
